// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl6mqWjmEJguhf0Wj2NKVElnm5xfvHqYc',
    appId: '1:429510229336:web:68d4a2e85c0c1cbec1792d',
    messagingSenderId: '429510229336',
    projectId: 'geni-app-x2',
    authDomain: 'geni-app-x2.firebaseapp.com',
    storageBucket: 'geni-app-x2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjQhPf1Fi_2fMe1JOh7kSUy1etRvFiGCc',
    appId: '1:429510229336:android:940c9e684b0d449ac1792d',
    messagingSenderId: '429510229336',
    projectId: 'geni-app-x2',
    storageBucket: 'geni-app-x2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNtl4kWM4iARTRohmjBKYR0ewOKwW6Dxg',
    appId: '1:429510229336:ios:c8319252d13462f4c1792d',
    messagingSenderId: '429510229336',
    projectId: 'geni-app-x2',
    storageBucket: 'geni-app-x2.appspot.com',
    iosBundleId: 'com.example.geniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNtl4kWM4iARTRohmjBKYR0ewOKwW6Dxg',
    appId: '1:429510229336:ios:c8319252d13462f4c1792d',
    messagingSenderId: '429510229336',
    projectId: 'geni-app-x2',
    storageBucket: 'geni-app-x2.appspot.com',
    iosBundleId: 'com.example.geniApp',
  );
}
